# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from pyspark.sql.types import StructType, StructField, DoubleType, StringType, IntegerType

WEATHER_FORECAST_SCHEMA = StructType(
    [
        # StructField("Class", StringType(), True),
        # StructField("Clds", IntegerType(), True),
        # StructField("Day_Ind", StringType(), True),
        # StructField("Dewpt", IntegerType(), True),
        # StructField("Dow", StringType(), True),
        # StructField("Expire_Time_Gmt", IntegerType(), True),
        # StructField("Fcst_Valid", IntegerType(), True),
        # StructField("Fcst_Valid_Local", StringType(), True),
        # StructField("Feels_Llike", IntegerType(), True),
        # StructField("Golf_Category", StringType(), True),
        # StructField("Golf_Index", DoubleType(), True),
        # StructField("Gust", DoubleType(), True),
        # StructField("Hi", IntegerType(), True),
        # StructField("Icon_Code", IntegerType(), True),
        # StructField("Icon_Extd", IntegerType(), True),
        # StructField("Mslp", DoubleType(), True),
        # StructField("Num", IntegerType(), True),
        # StructField("Phrase_12Char", StringType(), True),
        # StructField("Phrase_22Char", StringType(), True),
        # StructField("Phrase_32Char", StringType(), True),
        # StructField("Pop", StringType(), True),
        # StructField("Precip_Type", StringType(), True),
        # StructField("Qpf", DoubleType(), True),
        # StructField("Rh", IntegerType(), True),
        # StructField("Severity", IntegerType(), True),
        # StructField("Snow_Qpf", DoubleType(), True),
        # StructField("Subphrase_Pt1", StringType(), True),
        # StructField("Subphrase_Pt2", StringType(), True),
        # StructField("Subphrase_Pt3", StringType(), True),
        # StructField("Temp", IntegerType(), True),
        # StructField("Uv_Desc", StringType(), True),
        # StructField("Uv_Index", IntegerType(), True),
        # StructField("Uv_Index_Raw", DoubleType(), True),
        # StructField("Uv_Warning", IntegerType(), True),
        # StructField("Vis", DoubleType(), True),
        # StructField("Wc", IntegerType(), True),
        # StructField("Wdir", IntegerType(), True),
        # StructField("Wdir_Cardinal", StringType(), True),
        # StructField("Wspd", IntegerType(), True),
        # StructField("Wxman", StringType(), True),
        StructField("CLASS", StringType(), True),
        StructField("CLDS", IntegerType(), True),
        StructField("DAY_IND", StringType(), True),
        StructField("DEWPT", IntegerType(), True),
        StructField("DOW", StringType(), True),
        StructField("EXPIRE_TIME_GMT", IntegerType(), True),
        StructField("FCST_VALID", IntegerType(), True),
        StructField("FCST_VALID_LOCAL", StringType(), True),
        StructField("FEELS_LIKE", IntegerType(), True),
        StructField("GOLF_CATEGORY", StringType(), True),
        StructField("GOLF_INDEX", DoubleType(), True),
        StructField("GUST", DoubleType(), True),
        StructField("HI", IntegerType(), True),
        StructField("ICON_CODE", IntegerType(), True),
        StructField("ICON_EXTD", IntegerType(), True),
        StructField("MSLP", DoubleType(), True),
        StructField("NUM", IntegerType(), True),
        StructField("PHRASE_12CHAR", StringType(), True),
        StructField("PHRASE_22CHAR", StringType(), True),
        StructField("PHRASE_32CHAR", StringType(), True),
        StructField("POP", StringType(), True),
        StructField("PRECIP_TYPE", StringType(), True),
        StructField("QPF", DoubleType(), True),
        StructField("RH", IntegerType(), True),
        StructField("SEVERITY", IntegerType(), True),
        StructField("SNOW_QPF", DoubleType(), True),
        StructField("SUBPHRASE_PT1", StringType(), True),
        StructField("SUBPHRASE_PT2", StringType(), True),
        StructField("SUBPHRASE_PT3", StringType(), True),
        StructField("TEMP", IntegerType(), True),
        StructField("UV_DESC", StringType(), True),
        StructField("UV_INDEX", IntegerType(), True),
        StructField("UV_INDEX_RAW", DoubleType(), True),
        StructField("UV_WARNING", IntegerType(), True),
        StructField("VIS", DoubleType(), True),
        StructField("WC", IntegerType(), True),
        StructField("WDIR", IntegerType(), True),
        StructField("WDIR_CARDINAL", StringType(), True),
        StructField("WSPD", IntegerType(), True),
        StructField("WXMAN", StringType(), True),
    ]
)

WEATHER_FORECAST_MULTI_SCHEMA = StructType(
    [
        StructField("Latitude", DoubleType(), True),
        StructField("Longitude", DoubleType(), True),
        *WEATHER_FORECAST_SCHEMA.fields
    ]
)
